import requests
from selectolax.parser import HTMLParser
import pandas as pd
from sendmail import send_mail




def get_data(current):
    print('scraping started!')
    results = []
    url = "https://ecomm.sirim.my/SirimEnquiry/search_model.aspx"
    for i in range(1,3):
        payload =f"ctl00%24ContentPlaceHolder1%24TSM1=ctl00%24ContentPlaceHolder1%24UpdatePanel2%7Cctl00%24ContentPlaceHolder1%24gvResults%24ctl01%24lnkbtnApproveDate&=ContentPlaceHolder1_TSM1_HiddenField%3D&=ctl00%24userid%3D&=ctl00%24screenname%3D&=__EVENTARGUMENT%3D&=__LASTFOCUS%3D&ctl00%24ContentPlaceHolder1%24txtSearch1=%20&__EVENTTARGET=ctl00%24ContentPlaceHolder1%24gvResults%24ctl01%24lnkbtnApproveDate&__VIEWSTATE=%2FwEPDwUKMTEyNzUwMjIyNw8WBh4HU29ydEV4cAULQXBwcm92ZURhdGUeCVNvcnRPcmRlcgUDQVNDHhFjdXJyZW50UGFnZU51bWJlcgIBFgJmD2QWAgIDD2QWAgIOD2QWAgIDD2QWAmYPZBYGAg8PDxYCHgRUZXh0ZGRkAhUPDxYCHwNlZGQCHQ8WAh4HVmlzaWJsZWcWAmYPZBYCZg9kFhACAQ88KwARAwAPFgQeC18hRGF0YUJvdW5kZx4LXyFJdGVtQ291bnQCFGQBEBYAFgAWAAwUKwAAFgJmD2QWKgIBD2QWEmYPDxYCHwMFDkpUTS9OQS85OC8wNzA2ZGQCAQ9kFgICAQ8PFgIfAwUBMWRkAgIPZBYCAgEPDxYCHwMFHFRPWU9DT00gKE1BTEFZU0lBKSBTRE4uIEJIRC5kZAIDD2QWAgIBDw8WAh8DBRxJU0lUTyBDRC0xMiAoV0lUSCBDQUxMRVIgSUQpZGQCBA9kFgICAQ8PFgIfAwUFSVNJVE9kZAIFD2QWAgIBDw8WAh8DBQ9UQUdBLzY4Ri8wMzk5L01kZAIGD2QWAgIBDw8WAh8DBRVTSU5HTEUtTElORSBURUxFUEhPTkVkZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzI5LU1hci0yMDAyZGQCAg9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4MjdkZAIBD2QWAgIBDw8WAh8DBQEyZGQCAg9kFgICAQ8PFgIfAwUWSUJNIE1BTEFZU0lBIFNETi4gQkhELmRkAgMPZBYCAgEPDxYCHwMFE0NJU0NPIE5NLTJDRTFUMS1QUklkZAIED2QWAgIBDw8WAh8DBQ1DSVNDTyBTWVNURU1TZGQCBQ9kFgICAQ8PFgIfAwUPSVNNQi8wMUEvMDYwNC9TZGQCBg9kFgICAQ8PFgIfAwUZSVNETiBORVRXT1JLIE1PRFVMRSBFMS9UMWRkAgcPZBYCAgEPDxYCHwNlZGQCCA9kFgICAQ8PFgIfAwULMTgtTm92LTIwMTJkZAIDD2QWEmYPDxYCHwMFD1NRQVMvTkEvMDQvMDgzNWRkAgEPZBYCAgEPDxYCHwMFATNkZAICD2QWAgIBDw8WAh8DBRZJQk0gTUFMQVlTSUEgU0ROLiBCSEQuZGQCAw9kFgICAQ8PFgIfAwUUQ0lTQ08gTk0gLTFDRTFUMS1QUklkZAIED2QWAgIBDw8WAh8DBQ1DSVNDTyBTWVNURU1TZGQCBQ9kFgICAQ8PFgIfAwUPREFJUy8xMEEvMDYwNC9TZGQCBg9kFgICAQ8PFgIfAwUZSVNETiBORVRXT1JLIE1PRFVMRSBFMS9UMWRkAgcPZBYCAgEPDxYCHwNlZGQCCA9kFgICAQ8PFgIfAwULMTgtTm92LTIwMTJkZAIED2QWEmYPDxYCHwMFD1NRQVMvTkEvMDQvMDgzOWRkAgEPZBYCAgEPDxYCHwMFATRkZAICD2QWAgIBDw8WAh8DBSFEWEMgVEVDSE5PTE9HWSBNQUxBWVNJQSBTRE4uIEJIRC5kZAIDD2QWAgIBDw8WAh8DBRZDSVNDTyBWSUMyLTIgQlJJLU5UL1RFZGQCBA9kFgICAQ8PFgIfAwUNQ0lTQ08gU1lTVEVNU2RkAgUPZBYCAgEPDxYCHwMFEENFVFMvNjE1QS8wNjA0L1RkZAIGD2QWAgIBDw8WAh8DBRlJU0ROIFZPSUNFIElOVEVSRkFDRSBDQVJEZGQCBw9kFgICAQ8PFgIfA2VkZAIID2QWAgIBDw8WAh8DBQsxMC1BdWctMjAxNWRkAgUPZBYSZg8PFgIfAwUPU1FBUy9OQS8wNC8wODU2ZGQCAQ9kFgICAQ8PFgIfAwUBNWRkAgIPZBYCAgEPDxYCHwMFG0RFTEwgQVNJQSBQQUNJRklDIFNETi4gQkhELmRkAgMPZBYCAgEPDxYCHwMFEkNPTkVYQU5UIFJEMDEtRDYyMGRkAgQPZBYCAgEPDxYCHwMFCENPTkVYQU5UZGQCBQ9kFgICAQ8PFgIfAwUQQ0VUUy8wNjBBLzA3MDQvVGRkAgYPZBYCAgEPDxYCHwMFGUZBWC9EQVRBIE1PREVNLCA1NkssIFBTVE5kZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzA4LUp1bC0yMDA1ZGQCBg9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4NTlkZAIBD2QWAgIBDw8WAh8DBQE2ZGQCAg9kFgICAQ8PFgIfAwUhU0VSVlRPVUNILVdZV1kgKE1BTEFZU0lBKSBTRE4gQkhEZGQCAw9kFgICAQ8PFgIfAwULQUZJQ0lPIEZYMTZkZAIED2QWAgIBDw8WAh8DBQVSSUNPSGRkAgUPZBYCAgEPDxYCHwMFEENFVFMvMDU1QS8wNzA0L1RkZAIGD2QWAgIBDw8WAh8DBQlGQUNTSU1JTEVkZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzI0LUFwci0yMDA4ZGQCBw9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4NjBkZAIBD2QWAgIBDw8WAh8DBQE3ZGQCAg9kFgICAQ8PFgIfAwUhU0VSVlRPVUNILVdZV1kgKE1BTEFZU0lBKSBTRE4gQkhEZGQCAw9kFgICAQ8PFgIfAwU4RzMgSU5URVJGQUNFIFVOSVQgVFlQRSAyMDQ1IChGT1IgUklDT0ggQUZJQ0lPIDIwMzUvMjA0NSlkZAIED2QWAgIBDw8WAh8DBQVSSUNPSGRkAgUPZBYCAgEPDxYCHwMFEENFVFMvMDU2QS8wNzA0L1RkZAIGD2QWAgIBDw8WAh8DBRhGQUNTSU1JTEUgSU5URVJGQUNFIENBUkRkZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzIzLURlYy0yMDA2ZGQCCA9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4NjVkZAIBD2QWAgIBDw8WAh8DBQE4ZGQCAg9kFgICAQ8PFgIfAwUbRElHSVRBTE8gRU5URVJQUklTRSBTRE4gQkhEZGQCAw9kFgICAQ8PFgIfAwUHSEcgNTAwMGRkAgQPZBYCAgEPDxYCHwMFB0hZVU5EQUlkZAIFD2QWAgIBDw8WAh8DBRBDRVRTLzE1MEEvMDYwNC9SZGQCBg9kFgICAQ8PFgIfAwUbR1NNIDkwMC8xODAwIE1PQklMRSBTVEFUSU9OZGQCBw9kFgICAQ8PFgIfA2VkZAIID2QWAgIBDw8WAh8DBQsyNC1EZWMtMjAwNmRkAgkPZBYSZg8PFgIfAwUPU1FBUy9OQS8wNC8wODY2ZGQCAQ9kFgICAQ8PFgIfAwUBOWRkAgIPZBYCAgEPDxYCHwMFE1NFUlRJTkcgQ09NIFNETiBCSERkZAIDD2QWAgIBDw8WAh8DBQ1HQUxBWFkgVFg0NjZBZGQCBA9kFgICAQ8PFgIfAwUGR0FMQVhZZGQCBQ9kFgICAQ8PFgIfAwUQQ0VUUy8yNjZBLzA4MDQvUmRkAgYPZBYCAgEPDxYCHwMFE1ZIRiBQQUdJTkcgUkVDRUlWRVJkZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzI0LURlYy0yMDA2ZGQCCg9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4NzBkZAIBD2QWAgIBDw8WAh8DBQIxMGRkAgIPZBYCAgEPDxYCHwMFF1RFTEVTQ0lFTkNFIChNKSBTRE4gQkhEZGQCAw9kFgICAQ8PFgIfAwUTRy5TSERTTCBST1VURVIgNTExMGRkAgQPZBYCAgEPDxYCHwMFBUMtQ09NZGQCBQ9kFgICAQ8PFgIfAwUQQ0VUUy8wNDRBLzA3MDQvVGRkAgYPZBYCAgEPDxYCHwMFEUcuU0hEU0wgRVFVSVBNRU5UZGQCBw9kFgICAQ8PFgIfA2VkZAIID2QWAgIBDw8WAh8DBQsyNC1EZWMtMjAwNmRkAgsPZBYSZg8PFgIfAwUPU1FBUy9OQS8wNC8wODczZGQCAQ9kFgICAQ8PFgIfAwUCMTFkZAICD2QWAgIBDw8WAh8DBRZUQU1JQ08gU1lTVEVNUyBTRE4uQkhEZGQCAw9kFgICAQ8PFgIfAwUIR0UgMjk4NzhkZAIED2QWAgIBDw8WAh8DBQJHRWRkAgUPZBYCAgEPDxYCHwMFEENFVFMvMDQ2QS8wNjA0L1RkZAIGD2QWAgIBDw8WAh8DBRhURUxFUEhPTkUgQU5TV0VSSU5HIFVOSVRkZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzEzLVNlcC0yMDA4ZGQCDA9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4NzRkZAIBD2QWAgIBDw8WAh8DBQIxMmRkAgIPZBYCAgEPDxYCHwMFIlBIT05FIFNUQVIgQ09NTVVOSUNBVElPTiBTRE4uIEJIRC5kZAIDD2QWAgIBDw8WAh8DBQxTT05BVEEgS0Q4ODFkZAIED2QWAgIBDw8WAh8DBQZTT05BVEFkZAIFD2QWAgIBDw8WAh8DBRBDRVRTLzA5MUEvMDYwNC9SZGQCBg9kFgICAQ8PFgIfAwUbR1NNIDkwMC8xODAwIE1PQklMRSBTVEFUSU9OZGQCBw9kFgICAQ8PFgIfA2VkZAIID2QWAgIBDw8WAh8DBQsyMy1EZWMtMjAwNmRkAg0PZBYSZg8PFgIfAwUPU1FBUy9OQS8wNC8wODc1ZGQCAQ9kFgICAQ8PFgIfAwUCMTNkZAICD2QWAgIBDw8WAh8DBSJQSE9ORSBTVEFSIENPTU1VTklDQVRJT04gU0ROLiBCSEQuZGQCAw9kFgICAQ8PFgIfAwULU09OQVRBIEs4OTVkZAIED2QWAgIBDw8WAh8DBQZTT05BVEFkZAIFD2QWAgIBDw8WAh8DBRBDRVRTLzA3N0EvMDYwNC9SZGQCBg9kFgICAQ8PFgIfAwUbR1NNIDkwMC8xODAwIE1PQklMRSBTVEFUSU9OZGQCBw9kFgICAQ8PFgIfA2VkZAIID2QWAgIBDw8WAh8DBQsyMy1EZWMtMjAwNmRkAg4PZBYSZg8PFgIfAwUPU1FBUy9OQS8wNC8wODc2ZGQCAQ9kFgICAQ8PFgIfAwUCMTRkZAICD2QWAgIBDw8WAh8DBSJQSE9ORSBTVEFSIENPTU1VTklDQVRJT04gU0ROLiBCSEQuZGQCAw9kFgICAQ8PFgIfAwUMU0FHRU0gTVlYNS0yZGQCBA9kFgICAQ8PFgIfAwUFU0FHRU1kZAIFD2QWAgIBDw8WAh8DBRBDRVRTLzI3M0EvMDYwNC9SZGQCBg9kFgICAQ8PFgIfAwUgR1NNIDkwMC8xODAwLzE5MDAgTU9CSUxFIFNUQVRJT05kZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzIzLURlYy0yMDA2ZGQCDw9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4NzdkZAIBD2QWAgIBDw8WAh8DBQIxNWRkAgIPZBYCAgEPDxYCHwMFC0NDSyBUUkFESU5HZGQCAw9kFgICAQ8PFgIfAwULSkFCUkEgRlMyNThkZAIED2QWAgIBDw8WAh8DBQVKQUJSQWRkAgUPZBYCAgEPDxYCHwMFEENFVFMvMDA4QS8wNjA0L1JkZAIGD2QWAgIBDw8WAh8DBRNCTFVFVE9PVEggRVFVSVBNRU5UZGQCBw9kFgICAQ8PFgIfA2VkZAIID2QWAgIBDw8WAh8DBQsyNC1EZWMtMjAwNmRkAhAPZBYSZg8PFgIfAwUPU1FBUy9OQS8wNC8wODc4ZGQCAQ9kFgICAQ8PFgIfAwUCMTZkZAICD2QWAgIBDw8WAh8DBRBYRVNURUMgU0ROLiBCSEQuZGQCAw9kFgICAQ8PFgIfAwUKU09VVEVDIFYxNmRkAgQPZBYCAgEPDxYCHwMFBlNPVVRFQ2RkAgUPZBYCAgEPDxYCHwMFEENFVFMvMDEyQS8wNjA0L1JkZAIGD2QWAgIBDw8WAh8DBRtHU00gOTAwLzE4MDAgTU9CSUxFIFNUQVRJT05kZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzIzLURlYy0yMDA2ZGQCEQ9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4OTBkZAIBD2QWAgIBDw8WAh8DBQIxN2RkAgIPZBYCAgEPDxYCHwMFH1ZFTk8gVFJBRElORyAmIFRSQU5TUE9SVCBBR0VOQ1lkZAIDD2QWAgIBDw8WAh8DBRNOT0tJQSA2NjAwIChOSEwtMTApZGQCBA9kFgICAQ8PFgIfAwUFTk9LSUFkZAIFD2QWAgIBDw8WAh8DBRBDRVRTLzA3M0EvMDYwNC9UZGQCBg9kFgICAQ8PFgIfAwUgR1NNIDkwMC8xODAwLzE5MDAgTU9CSUxFIFNUQVRJT05kZAIHD2QWAgIBDw8WAh8DZWRkAggPZBYCAgEPDxYCHwMFCzEzLUp1bi0yMDA1ZGQCEg9kFhJmDw8WAh8DBQ9TUUFTL05BLzA0LzA4OTJkZAIBD2QWAgIBDw8WAh8DBQIxOGRkAgIPZBYCAgEPDxYCHwMFH1ZFTk8gVFJBRElORyAmIFRSQU5TUE9SVCBBR0VOQ1lkZAIDD2QWAgIBDw8WAh8DBRdOT0tJQSAzNjYwIChUWVBFIE5ITC04KWRkAgQPZBYCAgEPDxYCHwMFBU5PS0lBZGQCBQ9kFgICAQ8PFgIfAwUQQ0VUUy8wNjhBLzA2MDQvUmRkAgYPZBYCAgEPDxYCHwMFIEdTTSA5MDAvMTgwMC8xOTAwIE1PQklMRSBTVEFUSU9OZGQCBw9kFgICAQ8PFgIfA2VkZAIID2QWAgIBDw8WAh8DBQswMy1KdW4tMjAwNWRkAhMPZBYSZg8PFgIfAwUPU1FBUy9OQS8wNC8wODkzZGQCAQ9kFgICAQ8PFgIfAwUCMTlkZAICD2QWAgIBDw8WAh8DBS9LT05JQ0EgTUlOT0xUQSBCVVNJTkVTUyBTT0xVVElPTlMgKE0pIFNETi4gQkhELmRkAgMPZBYCAgEPDxYCHwMFJ0ZYLTMgKEZPUiBLT05JQ0EgTUlOT0xUQSBEaTIwMTEvRGkxNjExKWRkAgQPZBYCAgEPDxYCHwMFDktPTklDQSBNSU5PTFRBZGQCBQ9kFgICAQ8PFgIfAwUQQ0VUUy8wOTlBLzA4MDQvVGRkAgYPZBYCAgEPDxYCHwMFGEZBQ1NJTUlMRSBJTlRFUkZBQ0UgQ0FSRGRkAgcPZBYCAgEPDxYCHwNlZGQCCA9kFgICAQ8PFgIfAwULMTAtQXVnLTIwMDVkZAIUD2QWEmYPDxYCHwMFD1NRQVMvTkEvMDQvMDg5OGRkAgEPZBYCAgEPDxYCHwMFAjIwZGQCAg9kFgICAQ8PFgIfAwUaSUJDIFNPTEFSIFRFS05JSyBTRE4uIEJIRC5kZAIDD2QWAgIBDw8WAh8DBR9TT05ZIEVSSUNTU09OIEdNMjkgKDYxMDA1MDMtQlYpZGQCBA9kFgICAQ8PFgIfAwUNU09OWSBFUklDU1NPTmRkAgUPZBYCAgEPDxYCHwMFD1JBR1cvMTRBLzA2MDQvU2RkAgYPZBYCAgEPDxYCHwMFGEdTTSA5MDAvMTgwMCBSQURJTyBNT0RFTWRkAgcPZBYCAgEPDxYCHwNlZGQCCA9kFgICAQ8PFgIfAwULMDItT2N0LTIwMDdkZAIVDw8WAh8EaGRkAgMPDxYCHwRnZGQCBQ8PFgQeB0VuYWJsZWRoHwRnZGQCBw8PFgQfAwUBMR8EZ2RkAgsPDxYCHwRnZGQCDQ8PFgQfAwUEMzkyNR8EZ2RkAg8PDxYEHwRnHwdnZGQCEQ8PFgIfBGdkZBgBBSNjdGwwMCRDb250ZW50UGxhY2VIb2xkZXIxJGd2UmVzdWx0cw88KwAMAQgCAWT6xBoaCyIc3qqqOcvqkIv3rLsZJw%3D%3D&__VIEWSTATEGENERATOR=6EA7F05D&__ASYNCPOST=true&ctl00%24ContentPlaceHolder1%24SFcurrentpage={i}"
        headers = {
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.9",
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "Cookie": "cookiesession1=678A3E2E27008B684AD342808F663FAE; ASP.NET_SessionId=bexrri50hstymmbvomgo3w0d",
            "Origin": "https://ecomm.sirim.my",
            "Referer": "https://ecomm.sirim.my/SirimEnquiry/search_model.aspx",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
            "X-MicrosoftAjax": "Delta=true",
            "X-Requested-With": "XMLHttpRequest",
            "sec-ch-ua": '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "Content-Type": "application/x-www-form-urlencoded"
        }

        response = requests.request("POST", url, data=payload, headers=headers)

        html = HTMLParser(response.text)

        rows = html.css('table#ContentPlaceHolder1_gvResults tbody tr')
        brands = ['Samsung', 'Huawei', 'Honor', 'Xiaomi', 'Realme', 'Samusung', 'Redmi', 'Poco', 'Google', 'Apple', 'Vivo', 'Oppo', 'Oneplus', 'Motorola', 'Asus']
        for row in rows[1:]:
            profile = {}
            details = row.css('td')
            applicent_name = details[2].css_first('span').text()
            model_description = details[3].css_first('span').text()
            brand = details[4].css_first('span').text()
            aproval_code = details[5].css_first('span').text()
            device_cate = details[6].css_first('span').text()
            approval_date = details[7].css_first('span').text()
            expire_date = details[8].css_first('span').text()
            if brand.title() in brands:
                profile['applicent_name'] = applicent_name
                profile['model_description'] = model_description
                profile['brand'] = brand.upper()
                profile['aproval_code'] = aproval_code
                profile['device_cate'] = device_cate
                profile['approval_date'] = approval_date
                profile['expire_date'] = expire_date
                results.append(profile)
        print(f'Page number {i} is done!')
    
    df = pd.DataFrame(results)
    df.to_csv(current, index=False)

def compare_data(current, master):
    current_df = pd.read_csv(current)
    master_df = pd.read_csv(master)
    
    df_diff = current_df.merge(master_df, indicator=True, how='outer')
    compared_df = df_diff.loc[lambda x : x['_merge'] == 'left_only']
    isEmpty = len(compared_df)==0
    if not isEmpty:
        new_df = compared_df.iloc[:, [0, 1,2,3,4,5,6]]
        print(f'{len(new_df)} New data found {compared_df["aproval_code"]}')
        update_master_df = pd.concat([master_df, new_df])
        update_master_df.to_csv(master, index=False)
        send_mail(new_df)
    else:
        print('Data is up to date!')

    print('Data compared!')


def main():
    current_file = 'current.csv'
    master_file = 'master.csv'
    get_data(current_file)
    compare_data(current_file, master_file)


if __name__ == '__main__':
    main()